name = "elux-project-tracker"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "elux-tracker"
database_id = ""

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "elux-tracker-prod"
database_id = ""
