name = "elux-project-tracker"
pages_build_output_dir = "dist"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "elux-tracker-prod"
database_id = "23d01250-a87f-40d9-9490-9d2fa95ed5ce"
